# Generated by Django 4.1.1 on 2022-10-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=5)),
                ('personalid', models.CharField(max_length=10)),
            ],
        ),
    ]
