# Generated by Django 4.1.1 on 2022-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('parentphonenum', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradenumber', models.IntegerField()),
                ('student', models.ManyToManyField(to='eduware.student')),
                ('subject', models.ManyToManyField(to='eduware.subject')),
                ('teacher', models.ManyToManyField(to='eduware.teacher')),
            ],
            options={
                'ordering': ['gradenumber'],
            },
        ),
    ]
