# Generated by Django 4.1.1 on 2022-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='error@notcorrectlygenerated.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='error@notcorrectlygenerated.com', max_length=254),
        ),
    ]
