# Generated by Django 4.1.1 on 2022-10-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduware', '0002_student_email_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1)),
                ('alternate_id', models.IntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduware.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduware.teacher')),
            ],
        ),
    ]
