# Generated by Django 4.1.1 on 2022-11-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('eduware', '0002_rename_user_eduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EdUser',
            new_name='User',
        ),
    ]
