# Generated by Django 4.1.1 on 2022-10-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduware', '0003_remove_student_email_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduware.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduware.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduware.teacher')),
            ],
            options={
                'ordering': ['coursenumber'],
            },
        ),
    ]
