# Generated by Django 4.1.1 on 2022-10-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduware', '0004_studentsession_alter_course_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsession',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='studentsession',
            old_name='state',
            new_name='session_state',
        ),
    ]
